/* eslint-disable no-param-reassign */
// Import createSlice() from Redux toolkit:
import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import axios from '../../axios';

// Initial state for Redux store:
const initialState = {
  missions: [],
  isLoading: true,
  isMember: true,
  status: 'idle',
  error: '',
};

export const fetchMissions = createAsyncThunk(
  'missions/fetchMissions',
  async () => {
    const response = await axios.get('/missions');
    const missions = Object.keys(response.data).map((key) => ({
      mission_id: key,
      ...response.data[key],
    }));
    return missions.slice().sort((a, b) => a.mission_id - b.mission_id);
  },
);

// Create Redux state slice
const missionSlice = createSlice({
  name: 'missions',
  initialState, // Define initial state
  reducers: {
    // Define reducers
    // addMission: (state) => {
    //   state.missions = [...state.missions];
    // },
    membership: (state) => {
      state.isMember = !state.isMember;
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchMissions.pending, (state) => {
        state.isLoading = true;
        state.status = 'loading';
      })
      .addCase(fetchMissions.fulfilled, (state, action) => {
        state.isLoading = false;
        state.missions = action.payload;
        state.status = 'succeeded';
      })
      .addCase(fetchMissions.rejected, (state, action) => {
        state.isLoading = false;
        state.status = 'failed';
        state.error = action.error.message;
      });
  },
});

// Export actions generated by "createSlice()":
export const { membership } = missionSlice.actions;

// Export reducer generated by "createSlice()":
export default missionSlice.reducer;
